replace get-vm-ip.py with a bash script.

diff --git a/bin/get-vm-ip b/bin/get-vm-ip
--- a/bin/get-vm-ip
+++ b/bin/get-vm-ip
@@ -1,38 +1,17 @@
-#!/usr/bin/env python
-import os
+#!/bin/sh
+set -eu
 
-if not os.geteuid()==0:
-    sys.exit("\nyou must be root to run this\n")
-try:
-  from lxml import etree
-except ImportError:
-  import xml.etree.cElementTree as etree
-import libvirt
-import sys,subprocess,os
-import StringIO
+if [ "$#" -eq 0 ]; then
+  echo "provide vm name as argument."
+  exit 1
+fi
 
-debug = False
-parser = etree.XMLParser()
+mac=$(sudo virsh dumpxml $1 | grep "mac address" | head -1 | awk -F "'" '{print $2}')
 
-conn = libvirt.openReadOnly(None)
-if conn == None:
-  print 'Failed to open connection to the hypervisor'
-  sys.exit(1)
+arp -n | grep $mac > /dev/null
+if [ $? -ne 0 ]; then
+  echo "mac $mac not found"
+  exit 1
+fi
 
-domain=conn.lookupByName(sys.argv[1])
-desc = etree.fromstring(domain.XMLDesc(0))
-macAddr = desc.find("devices/interface[@type='network']/mac").attrib["address"].lower().strip()
-
-if debug:
-  print >>sys.stderr,"XMLDesc = %s" % macAddr
-
-output = subprocess.Popen(["arp", "-n"], stdout=subprocess.PIPE).communicate()[0]
-lines = [line.split() for line in output.split("\n")[1:]]
-if debug:
-  print lines
-IPaddr = [line[0] for line in lines if (line and (line[2] == macAddr))]
-if IPaddr:
-  print IPaddr[0]
-else:
-  sys.exit(1)
-
+arp -n | grep $mac | awk '{print $1}'
